export const ADD_FORM_SUCCESS = 'ADD_FORM_SUCCESS'
export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS'
export const DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS'

export const ADD_FORM_FAIL = 'ADD_FORM_FAIL'
export const GET_FORM_FAIL = 'GET_FORM_FAIL'
export const DELETE_FORM_FAIL = 'DELETE_FORM_FAIL'

// ***************** HOTSPOT ******************* //

export const CREATE_HOTSPOT_SUCCESS = 'CREATE_HOTSPOT_SUCCESS'
export const CREATE_HOTSPOT_FAIL = 'CREATE_HOTSPOT_FAIL'

export const GET_HOTSPOT_SUCCESS = 'GET_HOTSPOT_SUCCESS'
export const GET_HOTSPOT_FAIL = 'GET_HOTSPOT_FAIL'

export const UPDATE_HOTSPOT_SUCCESS = 'UPDATE_HOTSPOT_SUCCESS'
export const UPDATE_HOTSPOT_FAIL = 'UPDATE_HOTSPOT_FAIL'

export const DELETE_HOTSPOT_SUCCESS = 'DELETE_HOTSPOT_SUCCESS'
export const DELETE_HOTSPOT_FAIL = 'DELETE_HOTSPOT_FAIL'

// ***************** GROUP ******************* //

export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS'
export const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL'

export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS'
export const GET_GROUP_FAIL = 'GET_GROUP_FAIL'

export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
export const UPDATE_GROUP_FAIL = 'UPDATE_GROUP_FAIL'

export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL'

// ***************** ADMIN ******************* //

export const CREATE_ADMIN_SUCCESS = 'CREATE_ADMIN_SUCCESS'
export const CREATE_ADMIN_FAIL = 'CREATE_ADMIN_FAIL'

export const GET_ADMIN_SUCCESS = 'GET_ADMIN_SUCCESS'
export const GET_ADMIN_FAIL = 'GET_ADMIN_FAIL'

export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS'
export const UPDATE_ADMIN_FAIL = 'UPDATE_ADMIN_FAIL'

export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS'
export const DELETE_ADMIN_FAIL = 'DELETE_ADMIN_FAIL'

// ***************** DEVICE ******************* //

export const CREATE_DEVICE_SUCCESS = 'CREATE_DEVICE_SUCCESS'
export const CREATE_DEVICE_FAIL = 'CREATE_DEVICE_FAIL'

export const GET_DEVICE_SUCCESS = 'GET_DEVICE_SUCCESS'
export const GET_DEVICE_FAIL = 'GET_DEVICE_FAIL'

export const UPDATE_DEVICE_SUCCESS = 'UPDATE_DEVICE_SUCCESS'
export const UPDATE_DEVICE_FAIL = 'UPDATE_DEVICE_FAIL'

export const DELETE_DEVICE_SUCCESS = 'DELETE_DEVICE_SUCCESS'
export const DELETE_DEVICE_FAIL = 'DELETE_DEVICE_FAIL'
