export const ADD_FORM_SUCCESS = 'ADD_FORM_SUCCESS'
export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS'
export const DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS'

export const ADD_FORM_FAIL = 'ADD_FORM_FAIL'
export const GET_FORM_FAIL = 'GET_FORM_FAIL'
export const DELETE_FORM_FAIL = 'DELETE_FORM_FAIL'
